GET http://localhost:3001/
Content-Type: application/json

{
  "key": "value"
}

###

GET http://localhost:3001/api/places
Content-Type: application/json

###

POST http://localhost:3001/api/places
Content-Type: application/json

{
  ""
}
